version: '3.4'

services:
  eshopwcfservice:
    image: eshop/wcfservice
    build:
      context: ./src/eShopWCFService
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: willh/mssql-server-windows-developer:20H2