version: '3.4'

services:

  eshop.modernized.wcf:
    image: eshop/modernized-wcfservice:${TAG:-latest}
    build:
      context: ./deploy/wcf
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  eshop.modernized.webforms:
    image: eshop/modernized-webforms:${TAG:-latest}
    build:
      context: ./deploy/webforms
      dockerfile: Dockerfile
    depends_on:
      - sql.data      

  eshop.modernized.mvc:
    image: eshop/modernized-mvc:${TAG:-latest}
    build:
      context: ./deploy/mvc
      dockerfile: Dockerfile
    depends_on:
      - sql.data      
    
  sql.data:
    image: willh/mssql-server-windows-developer:20H2
